"""
Language support for Hebrew/English
"""
from typing import Dict, Any
from fastapi import Request

# Language translations
TRANSLATIONS = {
    "he": {
        "title": "מערכת אימייל 365",
        "dashboard": "לוח בקרה",
        "inbox": "תיבת דואר נכנס",
        "sent_items": "פריטים שנשלחו",
        "compose": "חיבור הודעה",
        "compose_email": "חיבור הודעה",
        "back_to_inbox": "חזרה לתיבת הדואר",
        "to_label": "אל",
        "cc_label": "עותק",
        "subject_label": "נושא",
        "message_label": "הודעה",
        "enter_recipient": "הזן כתובת אימייל של הנמען",
        "optional_cc": "נמעני עותק (לא חובה)",
        "enter_subject": "הזן נושא האימייל",
        "type_message": "הקלד את ההודעה כאן...",
        "save_draft": "שמור טיוטה",
        "clear": "נקה",
        "email_templates": "תבניות אימייל",
        "meeting_request": "בקשת פגישה",
        "follow_up": "מעקב",
        "urgent": "דחוף",
        "thank_you": "תודה",
        "quick_actions": "פעולות מהירות",
        "add_signature": "הוסף חתימה",
        "check_spelling": "בדיקת איות",
        "preview": "תצוגה מקדימה",
        "draft_saved_successfully": "הטיוטה נשמרה בהצלחה!",
        "please_fill_required": "אנא מלא את כל השדות הנדרשים לפני התצוגה המקדימה.",
        "email_preview": "תצוגה מקדימה של אימייל",
        "preview_generated": "נוצרה תצוגה מקדימה! בדוק את תוכן האימייל למעלה.",
        "deleted_items": "פריטים שנמחקו",
        "logout": "התנתקות",
        "api_docs": "תיעוד API",
        "welcome": "ברוכים הבאים",
        "email_system": "מערכת אימייל",
        "user": "משתמש",
        "home": "בית",
        "send_email": "שלח אימייל",
        "new_email": "אימייל חדש",
        "subject": "נושא",
        "to": "אל",
        "from": "מ",
        "date": "תאריך",
        "read": "קרא",
        "unread": "לא נקרא",
        "delete": "מחק",
        "reply": "השב",
        "forward": "העבר",
        "compose_new": "חבר הודעה חדשה",
        "email_preview": "תצוגה מקדימה של אימייל",
        "loading": "טוען...",
        "error": "שגיאה",
        "success": "הצלחה",
        "save": "שמור",
        "cancel": "בטל",
        "send": "שלח",
        "back": "חזור",
        "next": "הבא",
        "previous": "הקודם",
        "search": "חיפוש",
        "filter": "סינון",
        "sort": "מיון",
        "refresh": "רענן",
        "settings": "הגדרות",
        "help": "עזרה",
        "about": "אודות",
        "contact": "צור קשר",
        "support": "תמיכה",
        "login": "התחברות",
        "register": "הרשמה",
        "username": "שם משתמש",
        "password": "סיסמה",
        "email": "אימייל",
        "full_name": "שם מלא",
        "confirm_password": "אשר סיסמה",
        "forgot_password": "שכחת סיסמה?",
        "remember_me": "זכור אותי",
        "sign_in": "התחבר",
        "sign_up": "הירשם",
        "create_account": "צור חשבון",
        "already_have_account": "כבר יש לך חשבון?",
        "dont_have_account": "אין לך חשבון?",
        "invalid_credentials": "פרטי התחברות לא נכונים",
        "registration_successful": "ההרשמה הושלמה בהצלחה",
        "login_successful": "התחברת בהצלחה",
        "logout_successful": "התנתקת בהצלחה",
        "email_sent": "האימייל נשלח בהצלחה",
        "email_deleted": "האימייל נמחק",
        "email_marked_read": "האימייל סומן כנקרא",
        "no_emails": "אין אימיילים",
        "no_emails_inbox": "אין אימיילים בתיבת הדואר הנכנס",
        "no_emails_sent": "אין אימיילים שנשלחו",
        "no_emails_deleted": "אין אימיילים שנמחקו",
        "email_not_found": "האימייל לא נמצא",
        "error_occurred": "אירעה שגיאה",
        "try_again": "נסה שוב",
        "contact_support": "צור קשר עם התמיכה",
        "page_not_found": "הדף לא נמצא",
        "access_denied": "הגישה נדחתה",
        "session_expired": "הפגישה פגה",
        "please_login": "אנא התחבר",
        "language": "שפה",
        "hebrew": "עברית",
        "english": "אנגלית",
        "select_language": "בחר שפה",
        "rtl": "rtl",
        "ltr": "ltr",
        "welcome": "ברוכים הבאים",
        "welcome_message": "אתה מחובר כ",
        "welcome_instructions": "התחל בחיבור אימייל חדש או בדיקת תיבת הדואר הנכנס שלך",
        "inbox_description": "בדוק את האימיילים הנכנסים שלך",
        "sent_items_description": "צפה באימיילים שנשלחו",
        "compose_description": "כתוב אימייל חדש",
        "view_inbox": "צפה בתיבת דואר נכנס",
        "view_sent": "צפה בנשלחים",
        "email_statistics": "סטטיסטיקות אימייל",
        "inbox_emails": "אימיילים נכנסים",
        "sent_emails": "אימיילים שנשלחו",
        "unread_emails": "אימיילים לא נקראו",
        "total_emails": "סך הכל אימיילים",
        "recent_activity": "פעילות אחרונה",
        "loading_recent_emails": "טוען אימיילים אחרונים...",
        "error_loading_emails": "שגיאה בטעינת אימיילים",
        "no_emails_yet": "אין אימיילים עדיין",
            "compose_first_email": "חבר את האימייל הראשון שלך",
            "all": "הכל",
            "new": "חדש",
            "no_emails_inbox": "אין אימיילים בתיבת הדואר הנכנס",
            "no_emails_sent": "אין אימיילים שנשלחו",
            "no_emails_deleted": "אין אימיילים שנמחקו",
            "to_get_started": "כדי להתחיל",
            "deleted_emails_will_appear": "אימיילים שנמחקו יופיעו כאן"
        },
    "en": {
        "title": "365 Email System",
        "dashboard": "Dashboard",
        "inbox": "Inbox",
        "sent_items": "Sent Items",
        "compose": "Compose",
        "compose_email": "Compose Email",
        "back_to_inbox": "Back to Inbox",
        "to_label": "To",
        "cc_label": "CC",
        "subject_label": "Subject",
        "message_label": "Message",
        "enter_recipient": "Enter recipient email address",
        "optional_cc": "Optional CC recipients",
        "enter_subject": "Enter email subject",
        "type_message": "Type your message here...",
        "save_draft": "Save Draft",
        "clear": "Clear",
        "email_templates": "Email Templates",
        "meeting_request": "Meeting Request",
        "follow_up": "Follow-up",
        "urgent": "Urgent",
        "thank_you": "Thank You",
        "quick_actions": "Quick Actions",
        "add_signature": "Add Signature",
        "check_spelling": "Check Spelling",
        "preview": "Preview",
        "draft_saved_successfully": "Draft saved successfully!",
        "please_fill_required": "Please fill in all required fields before previewing.",
        "email_preview": "Email Preview",
        "preview_generated": "Preview generated! Check the email content above.",
        "deleted_items": "Deleted Items",
        "logout": "Logout",
        "api_docs": "API Docs",
        "welcome": "Welcome",
        "email_system": "Email System",
        "user": "User",
        "home": "Home",
        "send_email": "Send Email",
        "new_email": "New Email",
        "subject": "Subject",
        "to": "To",
        "from": "From",
        "date": "Date",
        "read": "Read",
        "unread": "Unread",
        "delete": "Delete",
        "reply": "Reply",
        "forward": "Forward",
        "compose_new": "Compose New",
        "email_preview": "Email Preview",
        "loading": "Loading...",
        "error": "Error",
        "success": "Success",
        "save": "Save",
        "cancel": "Cancel",
        "send": "Send",
        "back": "Back",
        "next": "Next",
        "previous": "Previous",
        "search": "Search",
        "filter": "Filter",
        "sort": "Sort",
        "refresh": "Refresh",
        "settings": "Settings",
        "help": "Help",
        "about": "About",
        "contact": "Contact",
        "support": "Support",
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "full_name": "Full Name",
        "confirm_password": "Confirm Password",
        "forgot_password": "Forgot Password?",
        "remember_me": "Remember Me",
        "sign_in": "Sign In",
        "sign_up": "Sign Up",
        "create_account": "Create Account",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "invalid_credentials": "Invalid credentials",
        "registration_successful": "Registration successful",
        "login_successful": "Login successful",
        "logout_successful": "Logout successful",
        "email_sent": "Email sent successfully",
        "email_deleted": "Email deleted",
        "email_marked_read": "Email marked as read",
        "no_emails": "No emails",
        "no_emails_inbox": "No emails in inbox",
        "no_emails_sent": "No sent emails",
        "no_emails_deleted": "No deleted emails",
        "email_not_found": "Email not found",
        "error_occurred": "An error occurred",
        "try_again": "Try again",
        "contact_support": "Contact support",
        "page_not_found": "Page not found",
        "access_denied": "Access denied",
        "session_expired": "Session expired",
        "please_login": "Please login",
        "language": "Language",
        "hebrew": "Hebrew",
        "english": "English",
        "select_language": "Select Language",
        "rtl": "ltr",
        "ltr": "ltr",
        "welcome": "Welcome",
        "welcome_message": "You're now logged in as",
        "welcome_instructions": "Start by composing a new email or checking your inbox",
        "inbox_description": "Check your incoming emails",
        "sent_items_description": "View your sent emails",
        "compose_description": "Write a new email",
        "view_inbox": "View Inbox",
        "view_sent": "View Sent",
        "email_statistics": "Email Statistics",
        "inbox_emails": "Inbox Emails",
        "sent_emails": "Sent Emails",
        "unread_emails": "Unread Emails",
        "total_emails": "Total Emails",
        "recent_activity": "Recent Activity",
        "loading_recent_emails": "Loading recent emails...",
        "error_loading_emails": "Error loading recent emails",
        "no_emails_yet": "No emails yet",
            "compose_first_email": "Compose your first email",
            "all": "All",
            "new": "New",
            "no_emails_inbox": "No emails in inbox",
            "no_emails_sent": "No emails sent",
            "no_emails_deleted": "No emails deleted",
            "to_get_started": "to get started",
            "deleted_emails_will_appear": "Deleted emails will appear here"
        }
    }

def get_language(request: Request) -> str:
    """Get current language from request"""
    # Check URL parameter first
    lang = request.query_params.get("lang", "he")  # Default to Hebrew
    if lang not in TRANSLATIONS:
        lang = "he"
    return lang

def get_translation(request: Request, key: str, **kwargs) -> str:
    """Get translation for current language"""
    lang = get_language(request)
    translation = TRANSLATIONS[lang].get(key, key)
    
    # Format with kwargs if provided
    if kwargs:
        try:
            return translation.format(**kwargs)
        except (KeyError, ValueError):
            return translation
    
    return translation

def get_direction(request: Request) -> str:
    """Get text direction for current language"""
    lang = get_language(request)
    return TRANSLATIONS[lang].get("rtl", "ltr")

def get_all_translations(request: Request) -> Dict[str, str]:
    """Get all translations for current language"""
    lang = get_language(request)
    return TRANSLATIONS[lang]
