"""
Language support for Hebrew/English
"""

from typing import Any, Dict

from fastapi import Request

# Language translations
TRANSLATIONS = {
    "he": {
        "app_name": "SkyShift.Dev",
        "title": "תפקיד",
        "dashboard": "לוח בקרה",
        "inbox": "תיבת דואר נכנס",
        "sent_items": "פריטים שנשלחו",
        "compose": "חיבור הודעה",
        "compose_email": "חיבור הודעה",
        "back_to_inbox": "חזרה לתיבת הדואר",
        "to_label": "אל",
        "cc_label": "עותק",
        "subject_label": "נושא",
        "message_label": "הודעה",
        "enter_recipient": "הזן כתובת אימייל של הנמען",
        "optional_cc": "נמעני עותק (לא חובה)",
        "enter_subject": "הזן נושא האימייל",
        "type_message": "הקלד את ההודעה כאן...",
        "save_draft": "שמור טיוטה",
        "clear": "נקה",
        "email_templates": "תבניות אימייל",
        "meeting_request": "בקשת פגישה",
        "follow_up": "מעקב",
        "urgent": "דחוף",
        "thank_you": "תודה",
        "quick_actions": "פעולות מהירות",
        "add_signature": "הוסף חתימה",
        "check_spelling": "בדיקת איות",
        "preview": "תצוגה מקדימה",
        "draft_saved_successfully": "הטיוטה נשמרה בהצלחה!",
        "please_fill_required": "אנא מלא את כל השדות הנדרשים לפני התצוגה המקדימה.",
        "email_preview": "תצוגה מקדימה של אימייל",
        "preview_generated": "נוצרה תצוגה מקדימה! בדוק את תוכן האימייל למעלה.",
        "deleted_items": "פריטים שנמחקו",
        "logout": "התנתקות",
        "api_docs": "תיעוד API",
        "welcome": "ברוכים הבאים ל",
        "email_system": "מערכת אימייל",
        "user": "משתמש",
        "home": "בית",
        "send_email": "שלח אימייל",
        "new_email": "אימייל חדש",
        "subject": "נושא",
        "to": "אל",
        "from": "מ",
        "date": "תאריך",
        "read": "קרא",
        "unread": "לא נקרא",
        "delete": "מחק",
        "reply": "השב",
        "forward": "העבר",
        "compose_new": "חבר הודעה חדשה",
        "email_preview": "תצוגה מקדימה של אימייל",
        "loading": "טוען...",
        "error": "שגיאה",
        "success": "הצלחה",
        "save": "שמור",
        "cancel": "בטל",
        "send": "שלח",
        "back": "חזור",
        "next": "הבא",
        "previous": "הקודם",
        "search": "חיפוש",
        "filter": "סינון",
        "sort": "מיון",
        "refresh": "רענן",
        "settings": "הגדרות",
        "help": "עזרה",
        "about": "אודות",
        "contact": "צור קשר",
        "support": "תמיכה",
        "login": "התחברות",
        "register": "הרשמה",
        "username": "שם משתמש",
        "password": "סיסמה",
        "email": "אימייל",
        "full_name": "שם מלא",
        "confirm_password": "אשר סיסמה",
        "forgot_password": "שכחת סיסמה?",
        "remember_me": "זכור אותי",
        "sign_in": "התחבר",
        "sign_up": "הירשם",
        "create_account": "צור חשבון",
        "already_have_account": "כבר יש לך חשבון?",
        "dont_have_account": "אין לך חשבון?",
        "invalid_credentials": "פרטי התחברות לא נכונים",
        "registration_successful": "ההרשמה הושלמה בהצלחה",
        "login_successful": "התחברת בהצלחה",
        "logout_successful": "התנתקת בהצלחה",
        "email_sent": "האימייל נשלח בהצלחה",
        "email_deleted": "האימייל נמחק",
        "email_marked_read": "האימייל סומן כנקרא",
        "no_emails": "אין אימיילים",
        "no_emails_inbox": "אין אימיילים בתיבת הדואר הנכנס",
        "no_emails_sent": "אין אימיילים שנשלחו",
        "no_emails_deleted": "אין אימיילים שנמחקו",
        "email_not_found": "האימייל לא נמצא",
        "error_occurred": "אירעה שגיאה",
        "try_again": "נסה שוב",
        "contact_support": "צור קשר עם התמיכה",
        "page_not_found": "הדף לא נמצא",
        "access_denied": "הגישה נדחתה",
        "session_expired": "הפגישה פגה",
        "please_login": "אנא התחבר",
        "language": "שפה",
        "hebrew": "עברית",
        "english": "אנגלית",
        "select_language": "בחר שפה",
        "rtl": "rtl",
        "ltr": "ltr",
        "welcome": "ברוכים הבאים",
        "welcome_message": "אתה מחובר כ",
        "welcome_instructions": "התחל בחיבור אימייל חדש או בדיקת תיבת הדואר הנכנס שלך",
        "inbox_description": "בדוק את האימיילים הנכנסים שלך",
        "sent_items_description": "צפה באימיילים שנשלחו",
        "compose_description": "כתוב אימייל חדש",
        "view_inbox": "צפה בתיבת דואר נכנס",
        "view_sent": "צפה בנשלחים",
        "email_statistics": "סטטיסטיקות אימייל",
        "inbox_emails": "אימיילים נכנסים",
        "sent_emails": "אימיילים שנשלחו",
        "unread_emails": "אימיילים לא נקראו",
        "total_emails": "סך הכל אימיילים",
        "recent_activity": "פעילות אחרונה",
        "loading_recent_emails": "טוען אימיילים אחרונים...",
        "error_loading_emails": "שגיאה בטעינת אימיילים",
        "no_emails_yet": "אין אימיילים עדיין",
        "compose_first_email": "חבר את האימייל הראשון שלך",
        "all": "הכל",
        "new": "חדש",
        "no_emails_inbox": "אין אימיילים בתיבת הדואר הנכנס",
        "no_emails_sent": "אין אימיילים שנשלחו",
        "no_emails_deleted": "אין אימיילים שנמחקו",
        "to_get_started": "כדי להתחיל",
        "deleted_emails_will_appear": "אימיילים שנמחקו יופיעו כאן",
        "contacts": "אנשי קשר",
        "add_contact": "הוסף איש קשר",
        "name": "שם",
        "first_name": "שם פרטי",
        "last_name": "שם משפחה",
        "email": "אימייל",
        "email_1": "אימייל 1",
        "email_2": "אימייל 2",
        "email_3": "אימייל 3",
        "mobile": "נייד",
        "phone": "טלפון",
        "business_phone": "טלפון עסקי",
        "home_phone": "טלפון בית",
        "company": "חברה",
        "department": "מחלקה",
        "app_name": "SkyShift.Dev",
        "title": "Title",
        "business_address": "כתובת עסקית",
        "home_address": "כתובת בית",
        "notes": "הערות",
        "folders": "תיקיות",
        "folder_name_prompt": "שם התיקייה",
        "no_contacts": "אין אנשי קשר",
        "add": "הוסף",
        "save": "שמור",
        "cancel": "בטל",
        "calendar": "לוח שנה",
        "calendar_coming_soon": "לוח שנה (בקרוב)",
        "add_event": "הוסף אירוע",
        "event": "אירוע",
        "events": "אירועים",
        "meeting": "פגישה",
        "appointment": "תור",
        "subject": "נושא",
        "start_time": "זמן התחלה",
        "end_time": "זמן סיום",
        "all_day": "כל היום",
        "location": "מיקום",
        "attendees": "משתתפים",
        "organizer": "מארגן",
        "reminder": "תזכורת",
        "recurring": "חוזר",
        "private": "פרטי",
        "confidential": "סודי",
        "normal": "רגיל",
        "high": "גבוה",
        "low": "נמוך",
        "free": "פנוי",
        "busy": "עסוק",
        "tentative": "זמני",
        "accepted": "מאושר",
        "declined": "נדחה",
        "today": "היום",
        "tomorrow": "מחר",
        "this_week": "השבוע",
        "next_week": "השבוע הבא",
        "this_month": "החודש",
        "next_month": "החודש הבא",
        "view": "תצוגה",
        "day_view": "תצוגת יום",
        "week_view": "תצוגת שבוע",
        "month_view": "תצוגת חודש",
        "agenda_view": "תצוגת סדר יום",
        "new_event": "אירוע חדש",
        "new_meeting": "פגישה חדשה",
        "edit_event": "ערוך אירוע",
        "delete_event": "מחק אירוע",
        "no_events": "אין אירועים",
        "no_events_today": "אין אירועים היום",
        "no_events_this_week": "אין אירועים השבוע",
        "upcoming_events": "אירועים קרובים",
        "recent_events": "אירועים אחרונים",
        "event_details": "פרטי האירוע",
        "meeting_details": "פרטי הפגישה",
        "online_meeting": "פגישה מקוונת",
        "teams_meeting": "פגישת Teams",
        "zoom_meeting": "פגישת Zoom",
        "meeting_url": "קישור לפגישה",
        "meeting_phone": "טלפון לפגישה",
        "response_required": "נדרשת תגובה",
        "response_sent": "תגובה נשלחה",
        "waiting_for_response": "ממתין לתגובה",
        "event_created": "האירוע נוצר",
        "event_updated": "האירוע עודכן",
        "event_deleted": "האירוע נמחק",
        "meeting_created": "הפגישה נוצרה",
        "meeting_updated": "הפגישה עודכנה",
        "meeting_deleted": "הפגישה נמחקה",
        "calendar_folders": "תיקיות לוח שנה",
        "default_calendar": "לוח שנה ברירת מחדל",
        "shared_calendar": "לוח שנה משותף",
        "public_calendar": "לוח שנה ציבורי",
        "private_calendar": "לוח שנה פרטי",
        "work_calendar": "לוח שנה עבודה",
        "personal_calendar": "לוח שנה אישי",
        "holiday_calendar": "לוח שנה חגים",
        "birthday_calendar": "לוח שנה ימי הולדת",
        "event_calendar": "לוח שנה אירועים",
        "meeting_calendar": "לוח שנה פגישות",
        "appointment_calendar": "לוח שנה תורים",
    },
    "en": {
        "app_name": "SkyShift.Dev",
        "title": "Title",
        "dashboard": "Dashboard",
        "inbox": "Inbox",
        "sent_items": "Sent Items",
        "compose": "Compose",
        "compose_email": "Compose Email",
        "back_to_inbox": "Back to Inbox",
        "to_label": "To",
        "cc_label": "CC",
        "subject_label": "Subject",
        "message_label": "Message",
        "enter_recipient": "Enter recipient email address",
        "optional_cc": "Optional CC recipients",
        "enter_subject": "Enter email subject",
        "type_message": "Type your message here...",
        "save_draft": "Save Draft",
        "clear": "Clear",
        "email_templates": "Email Templates",
        "meeting_request": "Meeting Request",
        "follow_up": "Follow-up",
        "urgent": "Urgent",
        "thank_you": "Thank You",
        "quick_actions": "Quick Actions",
        "add_signature": "Add Signature",
        "check_spelling": "Check Spelling",
        "preview": "Preview",
        "draft_saved_successfully": "Draft saved successfully!",
        "please_fill_required": "Please fill in all required fields before previewing.",
        "email_preview": "Email Preview",
        "preview_generated": "Preview generated! Check the email content above.",
        "deleted_items": "Deleted Items",
        "logout": "Logout",
        "api_docs": "API Docs",
        "welcome": "Welcome to",
        "email_system": "Email System",
        "user": "User",
        "home": "Home",
        "send_email": "Send Email",
        "new_email": "New Email",
        "subject": "Subject",
        "to": "To",
        "from": "From",
        "date": "Date",
        "read": "Read",
        "unread": "Unread",
        "delete": "Delete",
        "reply": "Reply",
        "forward": "Forward",
        "compose_new": "Compose New",
        "email_preview": "Email Preview",
        "loading": "Loading...",
        "error": "Error",
        "success": "Success",
        "save": "Save",
        "cancel": "Cancel",
        "send": "Send",
        "back": "Back",
        "next": "Next",
        "previous": "Previous",
        "search": "Search",
        "filter": "Filter",
        "sort": "Sort",
        "refresh": "Refresh",
        "settings": "Settings",
        "help": "Help",
        "about": "About",
        "contact": "Contact",
        "support": "Support",
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "full_name": "Full Name",
        "confirm_password": "Confirm Password",
        "forgot_password": "Forgot Password?",
        "remember_me": "Remember Me",
        "sign_in": "Sign In",
        "sign_up": "Sign Up",
        "create_account": "Create Account",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "invalid_credentials": "Invalid credentials",
        "registration_successful": "Registration successful",
        "login_successful": "Login successful",
        "logout_successful": "Logout successful",
        "email_sent": "Email sent successfully",
        "email_deleted": "Email deleted",
        "email_marked_read": "Email marked as read",
        "no_emails": "No emails",
        "no_emails_inbox": "No emails in inbox",
        "no_emails_sent": "No sent emails",
        "no_emails_deleted": "No deleted emails",
        "email_not_found": "Email not found",
        "error_occurred": "An error occurred",
        "try_again": "Try again",
        "contact_support": "Contact support",
        "page_not_found": "Page not found",
        "access_denied": "Access denied",
        "session_expired": "Session expired",
        "please_login": "Please login",
        "language": "Language",
        "hebrew": "Hebrew",
        "english": "English",
        "select_language": "Select Language",
        "rtl": "ltr",
        "ltr": "ltr",
        "welcome": "Welcome to",
        "welcome_message": "You're now logged in as",
        "welcome_instructions": "Start by composing a new email or checking your inbox",
        "inbox_description": "Check your incoming emails",
        "sent_items_description": "View your sent emails",
        "compose_description": "Write a new email",
        "view_inbox": "View Inbox",
        "view_sent": "View Sent",
        "email_statistics": "Email Statistics",
        "inbox_emails": "Inbox Emails",
        "sent_emails": "Sent Emails",
        "unread_emails": "Unread Emails",
        "total_emails": "Total Emails",
        "recent_activity": "Recent Activity",
        "loading_recent_emails": "Loading recent emails...",
        "error_loading_emails": "Error loading recent emails",
        "no_emails_yet": "No emails yet",
        "compose_first_email": "Compose your first email",
        "all": "All",
        "new": "New",
        "no_emails_inbox": "No emails in inbox",
        "no_emails_sent": "No emails sent",
        "no_emails_deleted": "No emails deleted",
        "to_get_started": "to get started",
        "deleted_emails_will_appear": "Deleted emails will appear here",
        "contacts": "Contacts",
        "add_contact": "Add Contact",
        "name": "Name",
        "first_name": "First Name",
        "last_name": "Last Name",
        "email": "Email",
        "email_1": "Email 1",
        "email_2": "Email 2",
        "email_3": "Email 3",
        "mobile": "Mobile",
        "phone": "Phone",
        "business_phone": "Business Phone",
        "home_phone": "Home Phone",
        "company": "Company",
        "department": "Department",
        "title": "Title",
        "business_address": "Business Address",
        "home_address": "Home Address",
        "notes": "Notes",
        "folders": "Folders",
        "folder_name_prompt": "Folder name",
        "no_contacts": "No contacts",
        "add": "Add",
        "save": "Save",
        "cancel": "Cancel",
        "calendar": "Calendar",
        "calendar_coming_soon": "Calendar (coming soon)",
        "add_event": "Add Event",
        "event": "Event",
        "events": "Events",
        "meeting": "Meeting",
        "appointment": "Appointment",
        "subject": "Subject",
        "start_time": "Start Time",
        "end_time": "End Time",
        "all_day": "All Day",
        "location": "Location",
        "attendees": "Attendees",
        "organizer": "Organizer",
        "reminder": "Reminder",
        "recurring": "Recurring",
        "private": "Private",
        "confidential": "Confidential",
        "normal": "Normal",
        "high": "High",
        "low": "Low",
        "free": "Free",
        "busy": "Busy",
        "tentative": "Tentative",
        "accepted": "Accepted",
        "declined": "Declined",
        "today": "Today",
        "tomorrow": "Tomorrow",
        "this_week": "This Week",
        "next_week": "Next Week",
        "this_month": "This Month",
        "next_month": "Next Month",
        "view": "View",
        "day_view": "Day View",
        "week_view": "Week View",
        "month_view": "Month View",
        "agenda_view": "Agenda View",
        "new_event": "New Event",
        "new_meeting": "New Meeting",
        "edit_event": "Edit Event",
        "delete_event": "Delete Event",
        "no_events": "No Events",
        "no_events_today": "No Events Today",
        "no_events_this_week": "No Events This Week",
        "upcoming_events": "Upcoming Events",
        "recent_events": "Recent Events",
        "event_details": "Event Details",
        "meeting_details": "Meeting Details",
        "online_meeting": "Online Meeting",
        "teams_meeting": "Teams Meeting",
        "zoom_meeting": "Zoom Meeting",
        "meeting_url": "Meeting URL",
        "meeting_phone": "Meeting Phone",
        "response_required": "Response Required",
        "response_sent": "Response Sent",
        "waiting_for_response": "Waiting for Response",
        "event_created": "Event Created",
        "event_updated": "Event Updated",
        "event_deleted": "Event Deleted",
        "meeting_created": "Meeting Created",
        "meeting_updated": "Meeting Updated",
        "meeting_deleted": "Meeting Deleted",
        "calendar_folders": "Calendar Folders",
        "default_calendar": "Default Calendar",
        "shared_calendar": "Shared Calendar",
        "public_calendar": "Public Calendar",
        "private_calendar": "Private Calendar",
        "work_calendar": "Work Calendar",
        "personal_calendar": "Personal Calendar",
        "holiday_calendar": "Holiday Calendar",
        "birthday_calendar": "Birthday Calendar",
        "event_calendar": "Event Calendar",
        "meeting_calendar": "Meeting Calendar",
        "appointment_calendar": "Appointment Calendar",
    },
}


def get_language(request: Request) -> str:
    """Get current language from request"""
    # Check URL parameter first
    lang = request.query_params.get("lang", "he")  # Default to Hebrew
    if lang not in TRANSLATIONS:
        lang = "he"
    return lang


def get_translation(request: Request, key: str, **kwargs) -> str:
    """Get translation for current language"""
    lang = get_language(request)
    translation = TRANSLATIONS[lang].get(key, key)

    # Format with kwargs if provided
    if kwargs:
        try:
            return translation.format(**kwargs)
        except (KeyError, ValueError):
            return translation

    return translation


def get_direction(request: Request) -> str:
    """Get text direction for current language"""
    lang = get_language(request)
    return TRANSLATIONS[lang].get("rtl", "ltr")


def get_all_translations(request: Request) -> Dict[str, str]:
    """Get all translations for current language"""
    lang = get_language(request)
    return TRANSLATIONS[lang]
